[package]
name = "sandbox-reflection"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
speedy = "0.8.3"

[dev-dependencies]
serde_json = "1.0"
