[advisories]

[bans]
deny = [
]

skip = [
    # two versions of glam for now since macaw is
    # unreleased for a little while, should fix soon
    { name = "glam" }
]

[sources]
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
]

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "Zlib",
]
exceptions = [
]
