[package]
name = "mirror-mirror"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
speedy = "0.8"
mirror-mirror-macros = { path = "../mirror-mirror-macros", version = "0.1.0" }

[dev-dependencies]
serde_json = "1.0"
